"""fourth migration

Revision ID: 671529a5fcb0
Revises: f11780510e42
Create Date: 2019-02-12 14:45:26.455387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671529a5fcb0'
down_revision = 'f11780510e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
